# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit AI Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language settings
language: en-US

# Review settings
reviews:
  # Enable reviews on all branches, not just the default branch
  review_status: true
  # Enable auto reviews on all target branches
  auto_review:
    enabled: true
    # Review all branches including non-default ones
    base_branches:
      - master
      - main
      - develop
      - "release-v*"
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"
  # Request changes threshold
  request_changes_workflow: false
  # Enable suggestions
  enable_free_tier: true

# What to review
review:
  # Enable review of different file types
  include_patterns:
    - "**/*.cs"
    - "**/*.csproj"
    - "**/*.sln"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.md"
    - "**/*.ps1"
    - "**/*.sh"
  
  # Skip certain files/directories
  exclude_patterns:
    - "**/bin/**"
    - "**/obj/**"
    - "**/*.user"
    - "**/*.suo"
    - "**/packages/**"
    - "**/.vs/**"
    - "**/node_modules/**"
    - "**/etc/docker/config/**"

# Chat settings
chat:
  # Enable chat functionality
  auto_reply: false

# Knowledge base
knowledge_base:
  # Custom guidelines for .NET projects
  guidelines:
    - "Follow C# coding conventions and naming standards"
    - "Ensure proper exception handling and logging"
    - "Check for potential security vulnerabilities"
    - "Verify dependency injection patterns are followed correctly"
    - "Review async/await usage for best practices"
    - "Ensure proper disposal of resources using 'using' statements"
    - "Check for null reference issues and defensive programming"
    - "Verify unit test coverage for new code"

# Early access features
early_access: true