// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mocklab.App.Data;

#nullable disable

namespace Mocklab.App.Data.Migrations
{
    [DbContext(typeof(MocklabDbContext))]
    [Migration("20260220221414_AddMockFoldersAndFolderIdToMockResponse")]
    partial class AddMockFoldersAndFolderIdToMockResponse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Mocklab.App.Models.MockCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_MockCollections_Name");

                    b.ToTable("MockCollections", "mocklab");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("IX_MockFolders_CollectionId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("MockFolders", "mocklab");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSequential")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryString")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("FolderId");

                    b.HasIndex("HttpMethod", "Route", "IsActive")
                        .HasDatabaseName("IX_MockResponses_HttpMethod_Route_IsActive");

                    b.ToTable("MockResponses", "mocklab");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponseRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionOperator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MockResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MockResponseId", "Priority")
                        .HasDatabaseName("IX_MockResponseRules_MockResponseId_Priority");

                    b.ToTable("MockResponseRules", "mocklab");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponseSequenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MockResponseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MockResponseId", "Order")
                        .HasDatabaseName("IX_MockResponseSequenceItems_MockResponseId_Order");

                    b.ToTable("MockResponseSequenceItems", "mocklab");
                });

            modelBuilder.Entity("Mocklab.App.Models.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedMockDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchedMockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryString")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_RequestLogs_Timestamp");

                    b.HasIndex("HttpMethod", "IsMatched")
                        .HasDatabaseName("IX_RequestLogs_HttpMethod_IsMatched");

                    b.ToTable("RequestLogs", "mocklab");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockFolder", b =>
                {
                    b.HasOne("Mocklab.App.Models.MockCollection", "Collection")
                        .WithMany("Folders")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mocklab.App.Models.MockFolder", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Collection");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponse", b =>
                {
                    b.HasOne("Mocklab.App.Models.MockCollection", null)
                        .WithMany("MockResponses")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mocklab.App.Models.MockFolder", null)
                        .WithMany("MockResponses")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponseRule", b =>
                {
                    b.HasOne("Mocklab.App.Models.MockResponse", "MockResponse")
                        .WithMany("Rules")
                        .HasForeignKey("MockResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockResponse");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponseSequenceItem", b =>
                {
                    b.HasOne("Mocklab.App.Models.MockResponse", "MockResponse")
                        .WithMany("SequenceItems")
                        .HasForeignKey("MockResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockResponse");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockCollection", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("MockResponses");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MockResponses");
                });

            modelBuilder.Entity("Mocklab.App.Models.MockResponse", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("SequenceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
