// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mocklab.App.Data;

#nullable disable

namespace Mocklab.App.Data.Migrations
{
    [DbContext(typeof(MocklabDbContext))]
    partial class MocklabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Mocklab.App.Models.MockResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("HttpMethod")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("QueryString");

                    b.Property<string>("RequestBody");

                    b.Property<string>("ResponseBody")
                        .IsRequired();

                    b.Property<string>("Route")
                        .IsRequired();

                    b.Property<int>("StatusCode");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("HttpMethod", "Route", "IsActive")
                        .HasDatabaseName("IX_MockResponses_HttpMethod_Route_IsActive");

                    b.ToTable("MockResponses", "mocklab");
                });
#pragma warning restore 612, 618
        }
    }
}
